// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = 'https://gmlvosodlnhllqbxtoum.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtbHZvc29kbG5obGxxYnh0b3VtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMwNzE0ODcsImV4cCI6MjA3ODY0NzQ4N30.j0SDXdCEr-vhe-Y_SU3qdWQsa5Cx6MuC5VMJfff2-x0';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});